# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ionut/workspace/Development/C/TestRequest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ionut/workspace/Development/C/TestRequest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ionut/workspace/Development/C/TestRequest/CMakeFiles /home/ionut/workspace/Development/C/TestRequest//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ionut/workspace/Development/C/TestRequest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestRequest

# Build rule for target.
TestRequest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRequest
.PHONY : TestRequest

# fast build rule for target.
TestRequest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/build
.PHONY : TestRequest/fast

#=============================================================================
# Target rules for targets named TestRequest_autogen

# Build rule for target.
TestRequest_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRequest_autogen
.PHONY : TestRequest_autogen

# fast build rule for target.
TestRequest_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest_autogen.dir/build.make CMakeFiles/TestRequest_autogen.dir/build
.PHONY : TestRequest_autogen/fast

TestRequest_autogen/mocs_compilation.o: TestRequest_autogen/mocs_compilation.cpp.o
.PHONY : TestRequest_autogen/mocs_compilation.o

# target to build an object file
TestRequest_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/TestRequest_autogen/mocs_compilation.cpp.o
.PHONY : TestRequest_autogen/mocs_compilation.cpp.o

TestRequest_autogen/mocs_compilation.i: TestRequest_autogen/mocs_compilation.cpp.i
.PHONY : TestRequest_autogen/mocs_compilation.i

# target to preprocess a source file
TestRequest_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/TestRequest_autogen/mocs_compilation.cpp.i
.PHONY : TestRequest_autogen/mocs_compilation.cpp.i

TestRequest_autogen/mocs_compilation.s: TestRequest_autogen/mocs_compilation.cpp.s
.PHONY : TestRequest_autogen/mocs_compilation.s

# target to generate assembly for a file
TestRequest_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/TestRequest_autogen/mocs_compilation.cpp.s
.PHONY : TestRequest_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/main.cpp.s
.PHONY : main.cpp.s

testrequestmainwindow.o: testrequestmainwindow.cpp.o
.PHONY : testrequestmainwindow.o

# target to build an object file
testrequestmainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/testrequestmainwindow.cpp.o
.PHONY : testrequestmainwindow.cpp.o

testrequestmainwindow.i: testrequestmainwindow.cpp.i
.PHONY : testrequestmainwindow.i

# target to preprocess a source file
testrequestmainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/testrequestmainwindow.cpp.i
.PHONY : testrequestmainwindow.cpp.i

testrequestmainwindow.s: testrequestmainwindow.cpp.s
.PHONY : testrequestmainwindow.s

# target to generate assembly for a file
testrequestmainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/testrequestmainwindow.cpp.s
.PHONY : testrequestmainwindow.cpp.s

ui/MainPage.o: ui/MainPage.cpp.o
.PHONY : ui/MainPage.o

# target to build an object file
ui/MainPage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/ui/MainPage.cpp.o
.PHONY : ui/MainPage.cpp.o

ui/MainPage.i: ui/MainPage.cpp.i
.PHONY : ui/MainPage.i

# target to preprocess a source file
ui/MainPage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/ui/MainPage.cpp.i
.PHONY : ui/MainPage.cpp.i

ui/MainPage.s: ui/MainPage.cpp.s
.PHONY : ui/MainPage.s

# target to generate assembly for a file
ui/MainPage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRequest.dir/build.make CMakeFiles/TestRequest.dir/ui/MainPage.cpp.s
.PHONY : ui/MainPage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... TestRequest_autogen"
	@echo "... TestRequest"
	@echo "... TestRequest_autogen/mocs_compilation.o"
	@echo "... TestRequest_autogen/mocs_compilation.i"
	@echo "... TestRequest_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... testrequestmainwindow.o"
	@echo "... testrequestmainwindow.i"
	@echo "... testrequestmainwindow.s"
	@echo "... ui/MainPage.o"
	@echo "... ui/MainPage.i"
	@echo "... ui/MainPage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

